// "use client";
import React from "react";
import "./styles/style.css";
import Header from "../components/Header.jsx";
import Footer from "../components/Footer.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, statusCode }) {
  if (statusCode === 404) {
    return <h1>404 Page not found</h1>;
  } else {
    return (
      <html lang="ja">
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    );
  }
}
